use rand::Rng;

pub const ADJECTIVES: &[&str] = &[
    "Adorable",
    "Beautiful",
    "Big",
    "Bright",
    "Clean",
    "Clever",
    "Cool",
    "Cute",
    "Cunning",
    "Determined",
    "Energetic",
    "Efficient",
    "Fantastic",
    "Fast",
    "Fine",
    "Fresh",
    "Good",
    "Gorgeous",
    "Great",
    "Handsome",
    "Hot",
    "Kind",
    "Lovely",
    "Mystic",
    "Neat",
    "Nice",
    "Patient",
    "Pretty",
    "Powerful",
    "Rich",
    "Secret",
    "Smart",
    "Solid",
    "Special",
    "Strategic",
    "Strong",
    "Tidy",
    "Wise",
];

pub const FRUITS: &[&str] = &[
    "Apple",
    "Avocado",
    "Banana",
    "Blackberry",
    "Blueberry",
    "Broccoli",
    "Carrot",
    "Cherry",
    "Coconut",
    "Grape",
    "Lemon",
    "Lettuce",
    "Mango",
    "Melon",
    "Mushroom",
    "Onion",
    "Orange",
    "Papaya",
    "Peach",
    "Pear",
    "Pineapple",
    "Potato",
    "Pumpkin",
    "Raspberry",
    "Strawberry",
    "Tomato",
];

pub fn generate_random_alias() -> String {
    let mut rng = rand::rng();
    let adj = ADJECTIVES[rng.random_range(0..ADJECTIVES.len())];
    let fruit = FRUITS[rng.random_range(0..FRUITS.len())];
    format!("{} {}", adj, fruit)
}
